steps:
  # Step 1: Install dependencies
  - name: 'python:3.9'
    id: 'Install Dependencies'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']

options:
  logging: CLOUD_LOGGING_ONLY
