steps:
  # Step 1: Install dependencies
  - name: 'python:3.9'
    id: 'Install Dependencies'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']
  # Step 2: Create the Dataflow Template
  - name: 'python:3.9'
    id: 'Create Dataflow Template'
    args:
      - 'python'
      - 'wordCount.py'  # Replace with your script name
      - '--runner'
      - 'DataflowRunner'
      - '--project'
      - '${_PROJECT_ID}'
      - '--region'
      - '${_REGION}'
      - '--temp_location'
      - 'gs://${_BUCKET}/temp/'
      - '--staging_location'
      - 'gs://${_BUCKET}/staging/'
      - '--template_location'
      - 'gs://${_BUCKET}/templates/wordcount_template'

options:
  logging: CLOUD_LOGGING_ONLY
