steps:
  - name: 'python:3.9'
    id: 'Install Dependencies and Create Dataflow Template'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Step 1: Install dependencies from requirements.txt
        pip install -r requirements.txt

        # Step 2: Create the Dataflow Template
        python wordCount.py \
          --runner DataflowRunner \
          --project ${_PROJECT_ID} \
          --region ${_REGION} \
          --temp_location gs://${_BUCKET}/temp/ \
          --staging_location gs://${_BUCKET}/staging/ \
          --template_location gs://${_BUCKET}/templates/wordcount_template_with_parameter


options:
  logging: CLOUD_LOGGING_ONLY
