steps:
  - name: 'python:3.9'
    id: 'Install Dependencies and Create Dataflow Template'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install dependencies from requirements.txt
        pip install -r requirements.txt

        # Create the Dataflow Template
        python wordCount.py \
          --runner DataflowRunner \
          --project ${_PROJECT_ID} \
          --region ${_REGION} \
          --temp_location gs://${_BUCKET}/temp/ \
          --staging_location gs://${_BUCKET}/staging/ \
          --template_location gs://${_BUCKET}/templates/wordcount_template \
          --input gs://${_BUCKET}/IO/input.txt \
          --output gs://${_BUCKET}/IO/output.txt 


options:
  logging: CLOUD_LOGGING_ONLY
