steps:
  # Step 1: Install dependencies from requirements.txt
  - name: 'python:3.9'
    id: 'Install Dependencies'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']

  # Step 2: Run the Dataflow pipeline to create the template
  - name: 'python:3.9'
    id: 'Run Dataflow Pipeline'
    entrypoint: 'python'
    args:
      - 'wordCount.py'  # Replace with your script name

